CREATE DATABASE IF NOT EXISTS instagram;
USE instagram;
CREATE TABLE user(
ID INT PRIMARY KEY,
AGE INT,
NAME VARCHAR(30) NOT NULL,
EMAIL_ID VARCHAR(50) UNIQUE,
FOLLOWERS INT DEFAULT 0,
FOLLOWING INT,
CONSTRAINT AGE_CHECK CHECK (AGE >= 18) 

);

CREATE TABLE post(
ID INT PRIMARY KEY,
CONTENT VARCHAR(100),
USER_ID INT,
FOREIGN KEY (USER_ID) REFERENCES user(ID)
);

INSERT INTO user
(ID ,AGE,NAME,EMAIL_ID,FOLLOWERS,FOLLOWING)
VALUES
(1,23,"ADAM","ADAM@YAHOO.IN",123,145),
(2,34,"ADNAN","ADNAN@OUTLOOK.COM",123,145),
(3,30,"BOB","BOB@GMAIL.COM",123,145),
(4,24,"ANKIT","ANKIT@YAHOO.IN",123,145);
#WE CANNOT ENTER DUPLICATE VALUES IN PRIMARY KEY 
#IT SHOULD BE UNIQUE 
-- INSERT INTO user
-- (ID,AGE,NAME)
-- VALUES
-- (2,20,"RANDOM");
SELECT DISTINCT AGE FROM user;